from PySide6.QtCore import (QCoreApplication,QMetaObject, QRect,QSize, Qt)
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (QLabel, QMenuBar,QPushButton, QSlider, QStatusBar,QWidget)

class Ui_Changer(object):
    def setupUi(self, Changer):
        if not Changer.objectName():
            Changer.setObjectName(u"Changer")
        Changer.resize(800, 600)
        Changer.setMinimumSize(QSize(800, 600))
        Changer.setMaximumSize(QSize(800, 600))
        font = QFont()
        font.setBold(False)
        Changer.setFont(font)
        self.centralwidget = QWidget(Changer)
        self.centralwidget.setObjectName(u"centralwidget")
        self.PlayPauseButton = QPushButton(self.centralwidget)
        self.PlayPauseButton.setObjectName(u"PlayPauseButton")
        self.PlayPauseButton.setGeometry(QRect(350, 460, 101, 31))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(False)
        self.PlayPauseButton.setFont(font1)
        self.PitchingSlider = QSlider(self.centralwidget)
        self.PitchingSlider.setObjectName(u"PitchingSlider")
        self.PitchingSlider.setGeometry(QRect(210, 350, 371, 22))
        self.PitchingSlider.setMaximum(24)
        self.PitchingSlider.setOrientation(Qt.Horizontal)
        self.PitchingSlider.setTickPosition(QSlider.TicksAbove)
        self.PitchingLabel = QLabel(self.centralwidget)
        self.PitchingLabel.setObjectName(u"PitchingLabel")
        self.PitchingLabel.setGeometry(QRect(320, 300, 151, 30))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.PitchingLabel.setFont(font2)
        self.PitchingLabel.setAlignment(Qt.AlignCenter)
        self.AcceptButton = QPushButton(self.centralwidget)
        self.AcceptButton.setObjectName(u"AcceptButton")
        self.AcceptButton.setGeometry(QRect(230, 460, 101, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        self.AcceptButton.setFont(font3)
        self.AmplitudeLabel = QLabel(self.centralwidget)
        self.AmplitudeLabel.setObjectName(u"AmplitudeLabel")
        self.AmplitudeLabel.setGeometry(QRect(320, 100, 151, 30))
        self.AmplitudeLabel.setFont(font2)
        self.AmplitudeLabel.setAlignment(Qt.AlignCenter)
        self.AmplitudeSlider = QSlider(self.centralwidget)
        self.AmplitudeSlider.setObjectName(u"AmplitudeSlider")
        self.AmplitudeSlider.setGeometry(QRect(210, 150, 371, 22))
        self.AmplitudeSlider.setMaximum(120)
        self.AmplitudeSlider.setSingleStep(10)
        self.AmplitudeSlider.setPageStep(10)
        self.AmplitudeSlider.setOrientation(Qt.Horizontal)
        self.AmplitudeSlider.setTickPosition(QSlider.TicksAbove)
        self.FrequencyLabel = QLabel(self.centralwidget)
        self.FrequencyLabel.setObjectName(u"FrequencyLabel")
        self.FrequencyLabel.setGeometry(QRect(320, 200, 151, 30))
        self.FrequencyLabel.setFont(font2)
        self.FrequencyLabel.setAlignment(Qt.AlignCenter)
        self.LoadButton = QPushButton(self.centralwidget)
        self.LoadButton.setObjectName(u"LoadButton")
        self.LoadButton.setGeometry(QRect(580, 510, 93, 29))
        self.CancelButton = QPushButton(self.centralwidget)
        self.CancelButton.setObjectName(u"CancelButton")
        self.CancelButton.setGeometry(QRect(690, 510, 93, 29))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 150, 41, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(610, 150, 51, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 350, 91, 20))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(590, 350, 81, 20))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(600, 250, 51, 20))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(150, 250, 51, 20))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 20, 121, 41))
        font4 = QFont()
        font4.setPointSize(16)
        font4.setBold(False)
        self.label_9.setFont(font4)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.FrequencySlider = QSlider(self.centralwidget)
        self.FrequencySlider.setObjectName(u"FrequencySlider")
        self.FrequencySlider.setGeometry(QRect(210, 250, 371, 22))
        self.FrequencySlider.setMaximum(199)
        self.FrequencySlider.setOrientation(Qt.Horizontal)
        self.FrequencySlider.setTickPosition(QSlider.TicksAbove)
        self.FrequencySlider.setTickInterval(10)
        self.TimeLabel = QLabel(self.centralwidget)
        self.TimeLabel.setObjectName(u"TimeLabel")
        self.TimeLabel.setGeometry(QRect(470, 460, 81, 31))
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(False)
        self.TimeLabel.setFont(font5)
        self.TimeLabel.setAlignment(Qt.AlignCenter)
        Changer.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Changer)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 26))
        Changer.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Changer)
        self.statusbar.setObjectName(u"statusbar")
        Changer.setStatusBar(self.statusbar)

        self.retranslateUi(Changer)

        QMetaObject.connectSlotsByName(Changer)
    # setupUi

    def retranslateUi(self, Changer):
        Changer.setWindowTitle(QCoreApplication.translate("Changer", u"Changer", None))
        self.PlayPauseButton.setText(QCoreApplication.translate("Changer", u"Play", None))
        self.PitchingLabel.setText(QCoreApplication.translate("Changer", u"Pitching", None))
        self.AcceptButton.setText(QCoreApplication.translate("Changer", u"Accept", None))
        self.AmplitudeLabel.setText(QCoreApplication.translate("Changer", u"Amplitude", None))
        self.FrequencyLabel.setText(QCoreApplication.translate("Changer", u"Frequency", None))
        self.LoadButton.setText(QCoreApplication.translate("Changer", u"Load", None))
        self.CancelButton.setText(QCoreApplication.translate("Changer", u"Cancel", None))
        self.label.setText(QCoreApplication.translate("Changer", u"0 db", None))
        self.label_2.setText(QCoreApplication.translate("Changer", u"120 db", None))
        self.label_3.setText(QCoreApplication.translate("Changer", u"-12 semitone", None))
        self.label_4.setText(QCoreApplication.translate("Changer", u"12 semitone", None))
        self.label_7.setText(QCoreApplication.translate("Changer", u"20 kHz", None))
        self.label_8.setText(QCoreApplication.translate("Changer", u"20 Hz", None))
        self.label_9.setText(QCoreApplication.translate("Changer", u"Changer", None))
        self.TimeLabel.setText(QCoreApplication.translate("Changer", u"00:00", None))
    # retranslateUi