from PySide6.QtCore import (QCoreApplication,QMetaObject, QRect,QSize, QTime, Qt)
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (QDateTimeEdit, QLabel, QPushButton,QSlider, QTimeEdit)

class Ui_Cutter(object):
    def setupUi(self, Cutter):
        if not Cutter.objectName():
            Cutter.setObjectName(u"Cutter")
        Cutter.resize(800, 400)
        Cutter.setMinimumSize(QSize(0, 0))
        Cutter.setMaximumSize(QSize(1000, 700))
        self.AudioSlider = QSlider(Cutter)
        self.AudioSlider.setObjectName(u"AudioSlider")
        self.AudioSlider.setGeometry(QRect(50, 70, 641, 31))
        self.AudioSlider.setMaximum(1000)
        self.AudioSlider.setPageStep(1)
        self.AudioSlider.setValue(0)
        self.AudioSlider.setOrientation(Qt.Horizontal)
        self.AudioSlider.setInvertedAppearance(False)
        self.AudioSlider.setInvertedControls(False)
        self.AudioSlider.setTickPosition(QSlider.NoTicks)
        self.AudioSlider.setTickInterval(0)
        self.CutterLabel = QLabel(Cutter)
        self.CutterLabel.setObjectName(u"CutterLabel")
        self.CutterLabel.setGeometry(QRect(330, 10, 130, 30))
        self.CutterLabel.setMinimumSize(QSize(130, 30))
        self.CutterLabel.setMaximumSize(QSize(130, 30))
        font = QFont()
        font.setPointSize(16)
        self.CutterLabel.setFont(font)
        self.CutterLabel.setAlignment(Qt.AlignCenter)
        self.CPPButton = QPushButton(Cutter)
        self.CPPButton.setObjectName(u"CPPButton")
        self.CPPButton.setGeometry(QRect(340, 120, 101, 31))
        self.BeginPosition = QTimeEdit(Cutter)
        self.BeginPosition.setObjectName(u"BeginPosition")
        self.BeginPosition.setGeometry(QRect(250, 230, 121, 31))
        self.BeginPosition.setMinimumSize(QSize(118, 0))
        self.BeginPosition.setMaximumTime(QTime(0, 59, 59))
        self.BeginPosition.setCurrentSection(QDateTimeEdit.MinuteSection)
        self.BeginPosLabel = QLabel(Cutter)
        self.BeginPosLabel.setObjectName(u"BeginPosLabel")
        self.BeginPosLabel.setGeometry(QRect(250, 200, 121, 20))
        self.BeginPosLabel.setAlignment(Qt.AlignCenter)
        self.EndPosition = QTimeEdit(Cutter)
        self.EndPosition.setObjectName(u"EndPosition")
        self.EndPosition.setGeometry(QRect(430, 230, 121, 31))
        self.EndPosition.setMinimumSize(QSize(118, 0))
        self.EndPosition.setMaximumTime(QTime(0, 59, 59))
        self.EndPosition.setCurrentSection(QDateTimeEdit.MinuteSection)
        self.EndPosLabel = QLabel(Cutter)
        self.EndPosLabel.setObjectName(u"EndPosLabel")
        self.EndPosLabel.setGeometry(QRect(430, 200, 121, 20))
        self.EndPosLabel.setAlignment(Qt.AlignCenter)
        self.CutButton = QPushButton(Cutter)
        self.CutButton.setObjectName(u"CutButton")
        self.CutButton.setGeometry(QRect(340, 280, 121, 31))
        self.EndLabel = QLabel(Cutter)
        self.EndLabel.setObjectName(u"EndLabel")
        self.EndLabel.setGeometry(QRect(700, 70, 61, 31))
        font1 = QFont()
        font1.setPointSize(11)
        self.EndLabel.setFont(font1)
        self.EndLabel.setAlignment(Qt.AlignCenter)
        self.BeginButton = QPushButton(Cutter)
        self.BeginButton.setObjectName(u"BeginButton")
        self.BeginButton.setGeometry(QRect(140, 230, 81, 31))
        self.EndButton = QPushButton(Cutter)
        self.EndButton.setObjectName(u"EndButton")
        self.EndButton.setGeometry(QRect(580, 230, 81, 31))
        self.CancelButton = QPushButton(Cutter)
        self.CancelButton.setObjectName(u"CancelButton")
        self.CancelButton.setGeometry(QRect(700, 360, 93, 29))
        self.LoadButton = QPushButton(Cutter)
        self.LoadButton.setObjectName(u"LoadButton")
        self.LoadButton.setGeometry(QRect(590, 360, 93, 29))

        self.retranslateUi(Cutter)

        QMetaObject.connectSlotsByName(Cutter)
    # setupUi

    def retranslateUi(self, Cutter):
        Cutter.setWindowTitle(QCoreApplication.translate("Cutter", u"Cutter", None))
        self.CutterLabel.setText(QCoreApplication.translate("Cutter", u"Cutter", None))
        self.CPPButton.setText(QCoreApplication.translate("Cutter", u"Play", None))
        self.BeginPosition.setDisplayFormat(QCoreApplication.translate("Cutter", u"mm:ss", None))
        self.BeginPosLabel.setText(QCoreApplication.translate("Cutter", u"Begin Position", None))
        self.EndPosition.setDisplayFormat(QCoreApplication.translate("Cutter", u"mm:ss", None))
        self.EndPosLabel.setText(QCoreApplication.translate("Cutter", u"End Position", None))
        self.CutButton.setText(QCoreApplication.translate("Cutter", u"Cut", None))
        self.EndLabel.setText(QCoreApplication.translate("Cutter", u"00:00", None))
        self.BeginButton.setText(QCoreApplication.translate("Cutter", u"Begin pos", None))
        self.EndButton.setText(QCoreApplication.translate("Cutter", u"End pos", None))
        self.CancelButton.setText(QCoreApplication.translate("Cutter", u"Cancel", None))
        self.LoadButton.setText(QCoreApplication.translate("Cutter", u"Load", None))
    # retranslateUi