from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, QSize)
from PySide6.QtGui import (QFont)
from PySide6.QtWidgets import (QComboBox, QLabel, QMenuBar, QPushButton, QStatusBar, QWidget)

class Ui_Manual(object):
    def setupUi(self, Manual):
        if not Manual.objectName():
            Manual.setObjectName(u"Manual_ui")
        Manual.resize(1000, 700)
        Manual.setMinimumSize(QSize(1000, 700))
        Manual.setMaximumSize(QSize(1000, 700))
        self.centralwidget = QWidget(Manual)
        self.centralwidget.setObjectName(u"centralwidget")
        self.NextButton = QPushButton(self.centralwidget)
        self.NextButton.setObjectName(u"NextButton")
        self.NextButton.setGeometry(QRect(562, 600, 90, 30))
        self.ReturnButton = QPushButton(self.centralwidget)
        self.ReturnButton.setObjectName(u"ReturnButton")
        self.ReturnButton.setGeometry(QRect(10, 610, 70, 30))
        self.ReturnButton.setMinimumSize(QSize(1, 1))
        self.ReturnButton.setMaximumSize(QSize(1000, 1000))
        font = QFont()
        font.setPointSize(10)
        self.ReturnButton.setFont(font)
        self.Pager = QComboBox(self.centralwidget)
        self.Pager.addItem("")
        self.Pager.addItem("")
        self.Pager.addItem("")
        self.Pager.addItem("")
        self.Pager.addItem("")
        self.Pager.addItem("")
        self.Pager.setObjectName(u"Pager")
        self.Pager.setGeometry(QRect(460, 600, 80, 30))
        self.PrevButton = QPushButton(self.centralwidget)
        self.PrevButton.setObjectName(u"PrevButton")
        self.PrevButton.setGeometry(QRect(350, 600, 90, 30))
        self.Pictures = QLabel(self.centralwidget)
        self.Pictures.setObjectName(u"Pictures")
        self.Pictures.setGeometry(QRect(20, 20, 960, 550))
        self.Pictures.setMinimumSize(QSize(960, 550))
        self.Pictures.setMaximumSize(QSize(960, 550))
        Manual.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Manual)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 26))
        Manual.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Manual)
        self.statusbar.setObjectName(u"statusbar")
        Manual.setStatusBar(self.statusbar)

        self.retranslateUi(Manual)

        QMetaObject.connectSlotsByName(Manual)
    # setupUi

    def retranslateUi(self, Manual):
        Manual.setWindowTitle(QCoreApplication.translate("Manual_ui", u"Manual", None))
        self.NextButton.setText(QCoreApplication.translate("Manual_ui", u"Next", None))
        self.ReturnButton.setText(QCoreApplication.translate("Manual_ui", u"Return", None))
        self.Pager.setItemText(0, QCoreApplication.translate("Manual_ui", u"1 page", None))
        self.Pager.setItemText(1, QCoreApplication.translate("Manual_ui", u"2 page", None))
        self.Pager.setItemText(2, QCoreApplication.translate("Manual_ui", u"3 page", None))
        self.Pager.setItemText(3, QCoreApplication.translate("Manual_ui", u"4 page", None))
        self.Pager.setItemText(4, QCoreApplication.translate("Manual_ui", u"5 page", None))
        self.Pager.setItemText(5, QCoreApplication.translate("Manual_ui", u"6 page", None))

        self.PrevButton.setText(QCoreApplication.translate("Manual_ui", u"Prev", None))
        self.Pictures.setText("")
    # retranslateUi
